[2024-04-26T22:58:19.511+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T22:58:19.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T22:58:20.011+0000] {logging_mixin.py:188} INFO - [2024-04-26T22:58:19.561+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T22:58:20.265+0000] {logging_mixin.py:188} INFO - [2024-04-26T22:58:20.220+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T22:58:20.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T22:58:20.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 1.179 seconds
[2024-04-26T22:58:50.763+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T22:58:50.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T22:58:50.792+0000] {logging_mixin.py:188} INFO - [2024-04-26T22:58:50.788+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T22:58:50.833+0000] {logging_mixin.py:188} INFO - [2024-04-26T22:58:50.825+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T22:58:50.835+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T22:58:50.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.199 seconds
[2024-04-26T22:59:21.025+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T22:59:21.026+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T22:59:21.029+0000] {logging_mixin.py:188} INFO - [2024-04-26T22:59:21.029+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T22:59:21.052+0000] {logging_mixin.py:188} INFO - [2024-04-26T22:59:21.047+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T22:59:21.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T22:59:21.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.061 seconds
[2024-04-26T22:59:51.560+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T22:59:51.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T22:59:51.564+0000] {logging_mixin.py:188} INFO - [2024-04-26T22:59:51.563+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T22:59:51.589+0000] {logging_mixin.py:188} INFO - [2024-04-26T22:59:51.584+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T22:59:51.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T22:59:51.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.060 seconds
[2024-04-26T23:00:21.789+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:00:21.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:00:21.792+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:00:21.792+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:00:21.808+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:00:21.804+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:00:21.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:00:21.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.044 seconds
[2024-04-26T23:00:51.982+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:00:51.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:00:51.985+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:00:51.985+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:00:52.005+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:00:52.001+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:00:52.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:00:52.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.052 seconds
[2024-04-26T23:01:22.126+0000] {processor.py:161} INFO - Started process (PID=398) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:01:22.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:01:22.129+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:01:22.129+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:01:22.144+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:01:22.141+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:01:22.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:01:22.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.043 seconds
[2024-04-26T23:01:52.421+0000] {processor.py:161} INFO - Started process (PID=457) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:01:52.422+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:01:52.424+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:01:52.424+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:01:52.440+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:01:52.437+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:01:52.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:01:52.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.048 seconds
[2024-04-26T23:02:23.073+0000] {processor.py:161} INFO - Started process (PID=516) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:02:23.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:02:23.076+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:02:23.076+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:02:23.095+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:02:23.091+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:02:23.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:02:23.121+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.055 seconds
[2024-04-26T23:02:53.212+0000] {processor.py:161} INFO - Started process (PID=575) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:02:53.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:02:53.216+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:02:53.215+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:02:53.236+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:02:53.230+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:02:53.238+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:02:53.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.058 seconds
[2024-04-26T23:03:23.505+0000] {processor.py:161} INFO - Started process (PID=634) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:03:23.506+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:03:23.507+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:03:23.507+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:03:23.522+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:03:23.519+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:03:23.524+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:03:23.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.044 seconds
[2024-04-26T23:03:53.811+0000] {processor.py:161} INFO - Started process (PID=693) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:03:53.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:03:53.814+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:03:53.814+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:03:53.832+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:03:53.829+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:03:53.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:03:53.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.047 seconds
[2024-04-26T23:04:13.520+0000] {processor.py:161} INFO - Started process (PID=744) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:04:13.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:04:13.523+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:04:13.523+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:04:13.551+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:04:13.547+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:04:13.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:04:13.571+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.057 seconds
[2024-04-26T23:04:43.610+0000] {processor.py:161} INFO - Started process (PID=803) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:04:43.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:04:43.613+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:04:43.613+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:04:43.632+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:04:43.627+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:04:43.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:04:43.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.050 seconds
[2024-04-26T23:05:14.092+0000] {processor.py:161} INFO - Started process (PID=856) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:05:14.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:05:14.097+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:05:14.097+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:05:14.120+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:05:14.116+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:05:14.121+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:05:14.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.066 seconds
[2024-04-26T23:05:44.596+0000] {processor.py:161} INFO - Started process (PID=915) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:05:44.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:05:44.600+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:05:44.600+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:05:44.620+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:05:44.615+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:05:44.622+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:05:44.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.055 seconds
[2024-04-26T23:09:54.057+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:09:54.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:09:54.066+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:09:54.065+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:09:54.097+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:09:54.091+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:09:54.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:09:54.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.099 seconds
[2024-04-26T23:10:24.647+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:10:24.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:10:24.653+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:10:24.652+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:10:24.673+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:10:24.669+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:10:24.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:10:24.698+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.060 seconds
[2024-04-26T23:10:55.283+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:10:55.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:10:55.286+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:10:55.285+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:10:55.302+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:10:55.299+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:10:55.304+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:10:55.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.046 seconds
[2024-04-26T23:11:25.510+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:11:25.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:11:25.514+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:11:25.514+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:11:25.533+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:11:25.529+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:11:25.535+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:11:25.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.050 seconds
[2024-04-26T23:11:55.591+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:11:55.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:11:55.594+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:11:55.594+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:11:55.610+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:11:55.606+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:11:55.611+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:11:55.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.041 seconds
[2024-04-26T23:12:25.968+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:12:25.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:12:25.971+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:12:25.971+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:12:25.985+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:12:25.982+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:12:25.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:12:26.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.044 seconds
[2024-04-26T23:12:56.113+0000] {processor.py:161} INFO - Started process (PID=392) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:12:56.114+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:12:56.116+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:12:56.115+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:12:56.134+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:12:56.130+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:12:56.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:12:56.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.048 seconds
[2024-04-26T23:13:26.408+0000] {processor.py:161} INFO - Started process (PID=451) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:13:26.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:13:26.411+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:13:26.410+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:13:26.431+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:13:26.427+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 11, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:13:26.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:13:26.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.054 seconds
[2024-04-26T23:17:52.290+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:17:52.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:17:52.294+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:17:52.294+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:17:52.328+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:17:52.324+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 12, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:17:52.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:17:52.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.068 seconds
[2024-04-26T23:18:22.656+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:18:22.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:18:22.661+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:18:22.661+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:18:22.684+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:18:22.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 12, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:18:22.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:18:22.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.065 seconds
[2024-04-26T23:18:45.836+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:18:45.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:18:45.840+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:18:45.839+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:18:45.872+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:18:45.867+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 10, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:18:45.873+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:18:45.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.064 seconds
[2024-04-26T23:19:41.754+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:19:41.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:19:41.758+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:19:41.758+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:19:41.784+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:19:41.779+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 10, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:19:41.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:19:41.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.064 seconds
[2024-04-26T23:20:11.892+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:20:11.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:20:11.894+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:20:11.894+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:20:11.910+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:20:11.907+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 10, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:20:11.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:20:11.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.040 seconds
[2024-04-26T23:20:42.326+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:20:42.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:20:42.329+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:20:42.329+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:20:42.352+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:20:42.347+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 10, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:20:42.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:20:42.371+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.051 seconds
[2024-04-26T23:21:12.503+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:21:12.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:21:12.507+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:21:12.506+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:21:12.526+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:21:12.522+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 10, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:21:12.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:21:12.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.049 seconds
[2024-04-26T23:21:42.981+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/mi_dag.py
[2024-04-26T23:21:42.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mi_dag.py for tasks to queue
[2024-04-26T23:21:42.984+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:21:42.984+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:21:43.000+0000] {logging_mixin.py:188} INFO - [2024-04-26T23:21:42.997+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/mi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mi_dag.py", line 10, in <module>
    from Primer_entregable import cargar_datos_spotify, cargar_datos_lastfm
ModuleNotFoundError: No module named 'Primer_entregable'
[2024-04-26T23:21:43.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mi_dag.py
[2024-04-26T23:21:43.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mi_dag.py took 0.066 seconds
